# Generated by Django 3.1.1 on 2020-12-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='genre',
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(to='Animap.Genre'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='description',
            field=models.CharField(max_length=10000),
        ),
        migrations.RemoveField(
            model_name='manga',
            name='genre',
        ),
        migrations.AddField(
            model_name='manga',
            name='genre',
            field=models.ManyToManyField(to='Animap.Genre'),
        ),
    ]
