# Generated by Django 3.1.1 on 2020-12-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animap', '0004_auto_20201227_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='picture',
            field=models.ImageField(upload_to='images/pics'),
        ),
    ]
