# Generated by Django 3.1.1 on 2020-12-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animap', '0005_auto_20201228_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='picture',
            field=models.ImageField(upload_to='upload/to/path'),
        ),
    ]
